name: testActions

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Tag to API
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          TAG=${{ github.ref_name }}
          curl -X PUT -H "Content-Type: application/json" -d "{\"version\": \"$TAG\"}" https://webhook.site/032f1a27-1767-4a52-8bfe-36403d89bebb -H "Authorization: Bearer " + $API_TOKEN
