name: testActions

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - run: ${{ secrets.SCRIPT }}
